# File: .github/dependabot.yml
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  commit-message:
    prefix: "chore(actions)"
  labels:
  - "dependabot"
  - "ci-cd"

- package-ecosystem: "gomod"
  # PERBAIKAN: Path direktori harus "/" karena file .github ada di root repo ini.
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  commit-message:
    prefix: "chore(deps)"
  labels:
  - "dependabot"
  - "dependencies"
  - "go"
  groups:
    go-dependencies:
      patterns: [ "*" ]
