# Nama workflow yang akan muncul di tab "Actions" GitHub
name: Go CI Pipeline

# Pemicu (Triggers)
# DIUBAH: Workflow sekarang berjalan untuk branch 'develop', 'main', dan branch fitur
on:
  push:
    branches:
    - main
    - develop
    - 'feature/**'
    - 'bugfix/**'
    - 'hotfix/**'
    - 'chore/**' # Ditambahkan untuk branch pemeliharaan seperti update dependensi

  pull_request:
    branches:
    - main
    - develop

jobs:
  # Nama job. Anda bisa menamainya apa saja. "build" adalah nama yang umum.
  # Nama ini akan digunakan di Branch Protection Rules.
  build:
    # Menggunakan runner terbaru yang disediakan GitHub
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Checkout kode repositori
    - name: Checkout repository
      uses: actions/checkout@v4

    # Langkah 2: Setup lingkungan Go
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' # Sesuaikan dengan versi Go Anda

    # Langkah 3: Menjalankan go mod tidy
    # Memastikan file go.mod dan go.sum bersih dan konsisten
    - name: Tidy Go Modules
      run: go mod tidy

    # Langkah 4: Menjalankan linter dengan golangci
    - name: Run linter
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    # Langkah 5: Menjalankan unit tests
    - name: Run unit tests with coverage
      run: go test -v ./... -coverprofile=coverage.out

    # Langkah 6 (Opsional): Mengunggah laporan cakupan
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out
